---
title: "R Notebook"
output: html_notebook
---

```{r}
1 + 1
1+1
1                         +1
rob_variable <- 1 + 1
rob_variable
rob_othervariable = 2 + 2
rob_othervariable
print("this is rob's variable")
rob_variable
rob_variable = rob_othervariable
print("this is rob's variable again")
rob_variable
rob_variable == rob_othervariable
1 > 2
1 == 2
1 < 2
1 != 2
x <- seq(0,5500, by = 5)
y <- seq(0,5500, by <- 5)
mean(x)
mean(c(1,2,3,4,5))
sum(x)
sd(x)
length(x)
SEM <- mean(x)/sqrt(length(x))
SEM
class(1)
class("a")
b <- "a"
class(b)
class(x)
z <- cbind(x,y)
class(z)
plot(x,y)
rob_listofletters <- c("a", "a", "f", "w", "a", "A", "sequins", "nileseldredge")
unique(rob_listofletters)
my_special_list <- unique(rob_listofletters)
```

```{r}
data()
data_iris <- iris
head(data_iris)
names(data_iris)
class(data_iris$Species)
unique(data_iris$Species)
levels(data_iris$Species)
mean(data_iris$Sepal.Length)
#summarize using aggregate()
data_iris_sepal <- do.call(data.frame,
aggregate(Sepal.Length~Species,
data = data_iris,
function(x)
c(mean = mean(x),
count = length(x),
SEM = sd(x)/sqrt(length(x)))))
data_iris_summary <- do.call(data.frame,
aggregate(cbind(Sepal.Length,Sepal.Width)~Species,
data = data_iris,
function(x)
c(mean = mean(x),
count = length(x),
SEM = sd(x)/sqrt(length(x)))))
#for demo purposes I am going to add a new factor to the dataset to show how to aggregate by multiple things
newcolumn <- rep(c(letters[1:3]),times=50)
data_iris_new <- cbind(data_iris,newcolumn)
data_iris_summary_new <- do.call(data.frame,
aggregate(cbind(Sepal.Length,Sepal.Width)~Species+newcolumn,
data = data_iris,
function(x)
c(mean = mean(x),
count = length(x),
SEM = sd(x)/sqrt(length(x)))))
data <- read.csv("data_week1.xlsx")
```

```{r}
#installing and loading packages
library(readxl)
data <- read_excel("data_week1.xlsx", skip = 9,
guess_max = 10000, #guessmax prevents columns with many initial banks being imported as a logical FALSE for not NAs)
na = " ") # you can put a period in the quotes if that is how you code blanks.
#You can load data from googledocs
#library(googlesheets4)
#Data_scouting <- read_sheet("put the URL here", skip = 0)
```
