---
title: "W2: data"
output: html_notebook
---

Goals:
-know ways to load in data just how you want it
-know how to diagnose and fix common problems
-basic cleanup to prep for graph or analysis


Philosophy:
-have ONE copy of your dataset. No v1, v2, _final, _finalfinal, _therealfinal, etc...


```{r Chunk 31 - loading your data}
#loading with read.csv()
data <- read.csv("data_week1.csv") #notice the first cell has some weird characters, this the file encoding for csvs and we don't want to read it
data <- read.csv("data_week1.csv", fileEncoding = 'UTF-8-BOM')

#installing and loading packages
library(readxl)

#loading with read_excel()
data <- read_excel("data_week1.xlsx", skip = 9,
guess_max = 10000, #guessmax prevents columns with many initial banks being imported as a logical FALSE for not NAs)
na = " ") # you can put a period in the quotes if that is how you code blanks.

#You can load data from googledocs
#library(googlesheets4)
#Data_scouting <- read_sheet("put the URL here", skip = 0)
```


library(readxl)
library(ggplot2)
Data <- read_excel("Fig 4.xlsx")
Data$Weeks <- as.character(Data$Weeks)
Data$Experimentlabel <- factor(Data$Experiment, labels=c(
               "A"=expression(paste("27 April field spray")),
               "B"=expression(paste("23 May field spray")),
               "C"=expression(paste("Potted tree spray "))))

ggplot(data = Data, aes(x = Weeks, y = minusddCT)) +
  #geom_errorbar(aes(ymin = Foldchange-SEM, ymax = Foldchange+SEM, group = Elicitor), width = 0, position=position_dodge(width=0.9)) +
  #geom_point(stat = "identity", shape = 21, color = 'black', aes(fill = Elicitor), position=position_dodge(width=0.5)) +
  geom_hline(yintercept = 0, linetype = 'dashed', size = 0.25) +
  geom_point(shape = 21, size = 2, aes(group = Elicitor), position=position_dodge(width=0.6)) +
  geom_errorbar(stat = "summary", fun.data = mean_se, aes(group = Elicitor), position=position_dodge(width=0.6), width=0) +
  geom_point(shape = 23, size = 2, stat = "summary", fun = "mean", color = 'black', aes(fill = Elicitor), position=position_dodge(width=0.6)) +
  facet_wrap(~Experimentlabel, ncol = 1, scales = 'free',labeller = label_parsed) +
  scale_fill_manual(values=c('black', 'grey')) +
  geom_blank(data = subset(Data, Experiment  == "A"), aes(y = 3)) +
  geom_blank(data = subset(Data, Experiment  == "B"), aes(y = 4, x = '1')) +
  geom_blank(data = subset(Data, Experiment  == "C"), aes(x = '7')) +
  scale_y_continuous(expression(paste("Relative ",italic("PR-1 "), "expression (-",paste(Delta),paste(Delta),"C"[T],")"))) +
  scale_x_discrete("\nWeeks post-treatment",breaks = c("0 (pre-spray)","1","3","7")) +
  theme_classic() +
  annotate("segment", x=-Inf, xend=Inf, y=-Inf, yend=-Inf, size = 0.75) +
  annotate("segment", x=-Inf, xend=-Inf, y=-Inf, yend=Inf, size = 0.75) +
  guides(fill=guide_legend(ncol=1)) +
  theme(
        #strip.text = element_blank(),
        #strip.background = element_blank(),
        strip.text = element_text(face = "bold"),
        #panel.border = element_rect(colour = "black", fill = NA),
        axis.line = element_line(colour = 'black', size = 0.5),
        axis.ticks = element_line(colour = "black"),
        axis.text.x = element_text(color = 'black'),
        axis.text.y = element_text(color = 'black'),
        strip.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA),
        legend.position=c(1,1), legend.justification=c(1,0),legend.box="vertical", legend.margin=margin(), legend.title = element_blank(), legend.key.size = unit(0.75, 'lines')
        #panel.spacing = unit(1.5, "lines")
        )

ggsave("Figure_4.tiff", width = 8, height = 12, units = "cm", dpi = 400, bg = "transparent")